#!/usr/bin/env python3
"""Package the automation system into a self-contained Windows executable.

This helper wraps ``pyinstaller`` with sensible defaults for the project and
injects sensitive configuration (for example Supabase credentials) directly into
``src/_embedded_env.py`` so that the generated executable can run without any
manual environment setup.
"""
from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
EMBEDDED_ENV_PATH = SRC_DIR / "_embedded_env.py"
DEFAULT_APP_NAME = "digital-chief"


def parse_dotenv(path: Path) -> Dict[str, str]:
    """Parse a minimal ``.env`` style file into a dictionary."""

    result: Dict[str, str] = {}
    if not path.exists():
        raise FileNotFoundError(f"Environment file not found: {path}")

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip("'\"")
        result[key] = value
    return result


def parse_inline_pairs(pairs: Iterable[str]) -> Dict[str, str]:
    """Parse ``KEY=VALUE`` command-line overrides."""

    result: Dict[str, str] = {}
    for item in pairs:
        if "=" not in item:
            raise ValueError(f"Inline override must be in KEY=VALUE format (got: {item})")
        key, value = item.split("=", 1)
        result[key.strip()] = value.strip()
    return result


def ensure_pyinstaller_available() -> str:
    """Return the path to the ``pyinstaller`` executable if it exists."""

    candidate = shutil.which("pyinstaller")
    if candidate:
        return candidate
    raise RuntimeError(
        "PyInstaller 未安装。请先运行 `pip install -r requirements-packaging.txt` 再继续。"
    )


def resolve_add_data_args() -> List[str]:
    """Build the ``--add-data`` arguments for PyInstaller."""

    entries: List[Tuple[Path, str]] = [
        (PROJECT_ROOT / "config", "config"),
        (PROJECT_ROOT / "data", "data"),
    ]

    args: List[str] = []
    separator = ";" if os.name == "nt" else ":"
    for src, target in entries:
        if not src.exists():
            continue
        args.extend(["--add-data", f"{src}{separator}{target}"])
    return args


def format_embedded_module(values: Dict[str, str]) -> str:
    """Render the Python source for ``_embedded_env.py`` with ``values``."""

    timestamp = datetime.utcnow().isoformat(timespec="seconds") + "Z"
    payload = ",\n    ".join(
        f"{json.dumps(key)}: {json.dumps(value)}" for key, value in sorted(values.items())
    )
    return (
        '"""Embedded environment fallbacks (auto-generated)."""\n'
        "from __future__ import annotations\n\n"
        "from typing import Dict\n\n"
        f"# Generated by scripts/package_windows_exe.py on {timestamp}\n"
        "EMBEDDED_ENV: Dict[str, str] = {\n"
        f"    {payload}\n"
        "}\n"
    )


def write_embedded_env(values: Dict[str, str]) -> str:
    """Overwrite ``_embedded_env.py`` and return the previous content."""

    previous = EMBEDDED_ENV_PATH.read_text(encoding="utf-8") if EMBEDDED_ENV_PATH.exists() else ""
    EMBEDDED_ENV_PATH.write_text(format_embedded_module(values), encoding="utf-8")
    return previous


def restore_embedded_env(previous: str) -> None:
    """Restore the original ``_embedded_env.py`` contents."""

    EMBEDDED_ENV_PATH.write_text(previous, encoding="utf-8")


def build_executable(args: argparse.Namespace, env_values: Dict[str, str]) -> None:
    """Invoke PyInstaller with the collected configuration."""

    pyinstaller = ensure_pyinstaller_available()

    dist_dir = (PROJECT_ROOT / "dist" / "windows").resolve()
    build_dir = (PROJECT_ROOT / "build" / "windows").resolve()
    dist_dir.mkdir(parents=True, exist_ok=True)
    build_dir.mkdir(parents=True, exist_ok=True)

    command: List[str] = [
        pyinstaller,
        "--noconfirm",
        "--clean",
        "--onefile",
        "--name",
        args.name or DEFAULT_APP_NAME,
        "--distpath",
        str(dist_dir),
        "--workpath",
        str(build_dir),
        "--specpath",
        str(build_dir),
        "--paths",
        str(SRC_DIR),
        "--hidden-import",
        "playwright.sync_api._generated",
        "--hidden-import",
        "amazon_product_parser",
        "--hidden-import",
        "core.amazon_product_parser",
        "--hidden-import",
        "playwright_helper",
        "--hidden-import",
        "openai",
        "--hidden-import",
        "requests",
        "--hidden-import",
        "bcrypt",
        "--collect-all",
        "playwright",
        "--collect-all",
        "openai",
    ]
    command.extend(resolve_add_data_args())
    command.append(str(SRC_DIR / "main.py"))

    env = os.environ.copy()
    env.update(env_values)

    print("🛠️ 运行打包命令:")
    print(" ".join(command))
    subprocess.run(command, check=True, cwd=PROJECT_ROOT, env=env)


def collect_env_values(args: argparse.Namespace) -> Dict[str, str]:
    """Collect and validate environment variables to embed."""

    collected: Dict[str, str] = {}

    for env_file in args.env_file:
        collected.update(parse_dotenv(Path(env_file)))

    collected.update({key: value for key, value in os.environ.items() if key.startswith("SUPABASE_")})

    inline_overrides = parse_inline_pairs(args.set or [])
    collected.update(inline_overrides)

    if args.supabase_url:
        collected["SUPABASE_URL"] = args.supabase_url
    if args.supabase_api_key:
        collected["SUPABASE_API_KEY"] = args.supabase_api_key

    required_keys = ["SUPABASE_URL", "SUPABASE_API_KEY"]
    missing = [key for key in required_keys if not collected.get(key)]
    if missing:
        raise RuntimeError(
            "缺少必要的 Supabase 配置: " + ", ".join(missing) +
            "。可以通过参数或 .env 文件提供，例如: --supabase-url ... --supabase-api-key ..."
        )

    return collected


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--supabase-url", help="Supabase 项目的 RESTful 访问地址")
    parser.add_argument("--supabase-api-key", help="Supabase 服务密钥")
    parser.add_argument(
        "--env-file",
        action="append",
        default=[],
        help="附加的 .env 文件路径（可多次指定，后者覆盖前者）",
    )
    parser.add_argument(
        "--set",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="额外嵌入的环境变量（可重复指定）",
    )
    parser.add_argument(
        "--name",
        default=DEFAULT_APP_NAME,
        help="生成的可执行文件名称（默认: digital-chief）",
    )
    parser.add_argument(
        "--keep-embedded",
        action="store_true",
        help="打包完成后保留写入的 _embedded_env.py（默认会自动还原）",
    )

    args = parser.parse_args(argv)

    if platform.system() != "Windows":
        print("⚠️ 当前系统并非 Windows。生成的可执行文件仍然以 Windows 为目标，但建议在 Windows 环境中执行打包。")

    env_values = collect_env_values(args)
    print("🔐 嵌入环境变量:", ", ".join(sorted(env_values.keys())))
    previous_content = write_embedded_env(env_values)

    try:
        build_executable(args, env_values)
        print("\n✅ 打包完成，生成的可执行文件位于 dist/windows 目录下。")
    finally:
        if args.keep_embedded:
            print("ℹ️ 按照参数要求，保留生成的 _embedded_env.py 文件。")
        else:
            restore_embedded_env(previous_content)

    return 0


if __name__ == "__main__":  # pragma: no cover - script entry point
    sys.exit(main())
